### ISSUE TITLE
CLI does not work with multi tsconfig config files

### ISSUE THREAD

**Issue by eugenenelou** [cschroeter/park-ui#385] opened 2024-07-20 13:57 UTC
Hi, I encountered a problem when trying to run the CLI command to add components.

It is returning me this error:

```
┌   Park UI v0.7.1
│
◇  Info ──────────────────────────────────────────────────────────────────────────────╮
┌   Park UI v0.7.1
│
◇  An error occurred
│
◇  Error Details ───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                           │
│  (FiberFailure) Error: { readonly compilerOptions: { readonly paths: { readonly [x: string]: ReadonlyArray<string> } } }  │
│  └─ ["compilerOptions"]                                                                                                   │
│     └─ { readonly paths: { readonly [x: string]: ReadonlyArray<string> } }      
```

I think it's related to my vite tsconfig files that is split in 2:

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

If I rename `tsconfig.app.json` into `ts.config.json`, the CLI works.

**Comment by cschroeter** [comment] 2024-07-24 18:31
Duplicate of https://github.com/cschroeter/park-ui/issues/377

**Closed by cschroeter** 2024-07-24 18:31 UTC
