### ISSUE TITLE
Cannot add components through cli for vue

### ISSUE THREAD

**Issue by robinpilz** [cschroeter/park-ui#349] opened 2024-06-21 16:49 UTC
Hi there,

first of all thanks for your efforts on the whole ecosystem, this is super exiting!

I tried to install it via the cli in my vue project using panda but there seem to be no registry files for vue.
https://park-ui.com/registry/panda/vue/components/index.json
Unexpected token T in JSON at position 0

Would be awesome if those could be added so one is able to play around with it a bit.
In general vue support seems to be a bit behind. I'd be happy to help bringing some of the components to vue but it would be nice to have some more examples on how to tackle different types of component compositions. I already failed at converting the Text component for example and also some others I tried.

Vue does not seem as straight forward as React yet, especially proper typescript integration using generics.

Edit:
Just copied the vue implementations in the repo and for the accordion I got the following typescript error:
![000141](https://github.com/cschroeter/park-ui/assets/60291821/cb2b9c8e-da88-418d-83a1-83cbe7df1b16)

Thanks!

**Comment by cschroeter** [comment] 2024-07-14 19:45
Duplicate of #155

**Closed by cschroeter** 2024-07-14 19:45 UTC
